services:
  postgres:
    image: postgres:18
    container_name: nstech-template-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nstech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - nstech-template-postgres-data:/var/lib/postgresql
    networks:
      - nstech-template-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nstech"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nstech-template-postgres-data:
    driver: local

networks:
  nstech-template-network:
    driver: bridge
