// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const dotenv = await import("dotenv");
const dotenvExpand = await import("dotenv-expand");

dotenvExpand.expand(dotenv.config());

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
